In [2]:
import numpy as np
import pandas as pd
from datetime import datetime

In [3]:
myyear = 2026
mymonth = 1
myday = 1
myhour = 2
mymin = 30
mysec = 15

In [4]:
mydate = datetime(myyear, mymonth, myday)
mydate

datetime.datetime(2026, 1, 1, 0, 0)

In [5]:
mydatetime = datetime(myyear,mymonth,myday, myhour,mymin,mysec)
mydatetime

datetime.datetime(2026, 1, 1, 2, 30, 15)

In [6]:
mydatetime.year

2026

In [7]:
myser = pd.Series(['Nov 3, 1990', '2000-01-01', None])

In [9]:
myser[0].year
# doesn't work: Pandas does not understand that the string is date info.

AttributeError: 'str' object has no attribute 'year'

In [12]:
timeser = pd.to_datetime(myser,format='mixed')

In [13]:
timeser[0].year

1990

In [14]:
euro_date = '31-12-2000'

In [15]:
pd.to_datetime(euro_date)

C:\Users\mvgarcia\AppData\Local\Temp\ipykernel_25240\1538865445.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(euro_date)

Timestamp('2000-12-31 00:00:00')

In [16]:
# Ambiguous date
ambi_date = '10-12-2000'

In [17]:
pd.to_datetime(ambi_date)

Timestamp('2000-10-12 00:00:00')

In [18]:
#got it wrong, so:
pd.to_datetime(ambi_date,dayfirst=True)

Timestamp('2000-12-10 00:00:00')

In [19]:
# ISO date
iso_date= '2026-10-12'

In [20]:
pd.to_datetime(iso_date)

Timestamp('2026-10-12 00:00:00')

In [23]:
style_date = '9--Dec--2000'
pd.to_datetime(style_date, format = '%d--%b--%Y')

Timestamp('2000-12-09 00:00:00')

In [24]:
custom_date = "11th of Dec 2000"
pd.to_datetime(custom_date)

Timestamp('2000-12-11 00:00:00')

In [25]:
sales = pd.read_csv('../jupyter_notebooks/03-Pandas/RetailSales_BeerWineLiquor.csv')
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [26]:
# Check the type
sales['DATE']
# they are strings

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: str

In [27]:
sales['DATE'] = pd.to_datetime(sales['DATE'])

In [29]:
sales['DATE']
# Now they are datetime64 object

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[us]

In [30]:
sales['DATE'][0].year

1992

In [31]:
sales['DATE'][7].month

8

### Parsing dates at read time

In [32]:
sales = pd.read_csv('../jupyter_notebooks/03-Pandas/RetailSales_BeerWineLiquor.csv', parse_dates=[0])

In [33]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[us]

In [34]:
sales = sales.set_index("DATE")

In [35]:
sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [41]:
# Now we can use "resample()" to aggregate data by time units according to different rules.
# 'YE' is "end of year" (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects)
sales.resample(rule='YE').mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

### Accessing datetime objects using the .dt method
All available features for a single python datetime object are also available Series- and Dataframe-wise by using the .dt. method

In [42]:
sales = pd.read_csv('../jupyter_notebooks/03-Pandas/RetailSales_BeerWineLiquor.csv', parse_dates=[0])
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [43]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[us]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 5.4 KB

In [44]:
sales['DATE'].dt.year

0      1992
1      1992
2      1992
3      1992
4      1992
       ...
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int32

In [45]:
sales['DATE'].dt.month

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int32

In [48]:
sales['DATE'].dt.day
# Seems all data points are at the beginning of the month

0      1
1      1
2      1
3      1
4      1
      ..
335    1
336    1
337    1
338    1
339    1
Name: DATE, Length: 340, dtype: int32

In [49]:
sales['DATE'].dt.hour
# no time of day information

0      0
1      0
2      0
3      0
4      0
      ..
335    0
336    0
337    0
338    0
339    0
Name: DATE, Length: 340, dtype: int32