# groupby() operations
groupby() allows to examine data per category

groupby() is lazy: it does not evaluate until there is something to do with it.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../jupyter_notebooks/03-Pandas/mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
# let's see what can be a category
for i in df.columns.values:
    print(df[i].unique())

[18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ]
[8 4 6 3 5]
[307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  90.  231.  262.  134.  119.  171.  115.  101.  305.   85.  130.  168.
 111.  260.  151.  146.   80.   78.  105.  131.  163.   89.  267.   86.
 183.  141.  173.  135.   81.  100.  145.  112.  181.  144. ]
<StringArray>
['130', '165', '150', '140', '198', '220', '215', '225', '190', '170', '160',
  '95',  '97',  '85',  '88',  '46',  '87',  '90', '113', '200', '210', '193',
   '?', '100', '105', '175', '153', '180', '110',  '72',  '86',  '70',  '76',
  '65',  '69',  '60',  '80',  '54', '208', '155', '112',  '92', '145', '137',
 '158', '167',  '94', '107', '230',  '49',  '75',  '91', '122',  '67',  '83',
  '78',  '52',  '61',  '93', '148', '129',  '96',  '71',  '98', '115',  '53',
  '81',  '79', '120', '152', '102', '108',  '68',  '58', '149',  '89',  '63',
  '48',  '66', '139', '103', '125', '133', '138', '135', '142',  '77',  '62',
 '132',  '84',  '64',  '74', '116',  '82']
Length: 94, dtype: str
[3504 3693 3436 3433 3449 4341 4354 4312 4425 3850 3563 3609 3761 3086
 2372 2833 2774 2587 2130 1835 2672 2430 2375 2234 2648 4615 4376 4382
 4732 2264 2228 2046 2634 3439 3329 3302 3288 4209 4464 4154 4096 4955
 4746 5140 2962 2408 3282 3139 2220 2123 2074 2065 1773 1613 1834 1955
 2278 2126 2254 2226 4274 4385 4135 4129 3672 4633 4502 4456 4422 2330
 3892 4098 4294 4077 2933 2511 2979 2189 2395 2288 2506 2164 2100 4100
 3988 4042 3777 4952 4363 4237 4735 4951 3821 3121 3278 2945 3021 2904
 1950 4997 4906 4654 4499 2789 2279 2401 2379 2124 2310 2472 2265 4082
 4278 1867 2158 2582 2868 3399 2660 2807 3664 3102 2875 2901 3336 2451
 1836 2542 3781 3632 3613 4141 4699 4457 4638 4257 2219 1963 2300 1649
 2003 2125 2108 2246 2489 2391 2000 3264 3459 3432 3158 4668 4440 4498
 4657 3907 3897 3730 3785 3039 3221 3169 2171 2639 2914 2592 2702 2223
 2545 2984 1937 3211 2694 2957 2671 1795 2464 2572 2255 2202 4215 4190
 3962 3233 3353 3012 3085 2035 3651 3574 3645 3193 1825 1990 2155 2565
 3150 3940 3270 2930 3820 4380 4055 3870 3755 2045 1945 3880 4060 4140
 4295 3520 3425 3630 3525 4220 4165 4325 4335 1940 2740 2755 2051 2075
 1985 2190 2815 2600 2720 1800 2070 3365 3735 3570 3535 3155 2965 3430
 3210 3380 3070 3620 3410 3445 3205 4080 2560 2230 2515 2745 2855 2405
 2830 3140 2795 2135 3245 2990 2890 3265 3360 3840 3725 3955 3830 4360
 4054 3605 1925 1975 1915 2670 3530 3900 3190 3420 2200 2150 2020 2595
 2700 2556 2144 1968 2120 2019 2678 2870 3003 3381 2188 2711 2434 2110
 2800 2085 2335 2950 3250 1850 2145 1845 2910 2420 2500 2905 2290 2490
 2635 2620 2725 2385 1755 1875 1760 2050 2215 2380 2320 2210 2350 2615
 3230 3160 2900 3415 3060 3465 2605 2640 2575 2525 2735 2865 3035 1980
 2025 1970 2160 2205 2245 1965 1995 3015 2585 2835 2665 2370 2790 2295
 2625]
[12.  11.5 11.  10.5 10.   9.   8.5  8.   9.5 15.  15.5 16.  14.5 20.5
 17.5 12.5 14.  13.5 18.5 19.  13.  19.5 18.  17.  23.5 16.5 21.  16.9
 14.9 17.7 15.3 13.9 12.8 15.4 17.6 22.2 22.1 14.2 17.4 16.2 17.8 12.2
 16.4 13.6 15.7 13.2 21.9 16.7 12.1 14.8 18.6 16.8 13.7 11.1 11.4 18.2
 15.8 15.9 14.1 21.5 14.4 19.4 19.2 17.2 18.7 15.1 13.4 11.2 14.7 16.6
 17.3 15.2 14.3 20.1 24.8 11.3 12.9 18.8 18.1 17.9 21.7 23.7 19.9 21.8
 13.8 12.6 16.1 20.7 18.3 20.4 19.6 17.1 15.6 24.6 11.6]
[70 71 72 73 74 75 76 77 78 79 80 81 82]
[1 3 2]
<StringArray>
[ 'chevrolet chevelle malibu',          'buick skylark 320',
         'plymouth satellite',              'amc rebel sst',
                'ford torino',           'ford galaxie 500',
           'chevrolet impala',          'plymouth fury iii',
           'pontiac catalina',         'amc ambassador dpl',
 ...
 'chrysler lebaron medallion',             'ford granada l',
           'toyota celica gt',          'dodge charger 2.2',
           'chevrolet camaro',            'ford mustang gl',
                  'vw pickup',              'dodge rampage',
                'ford ranger',                 'chevy s-10']
Length: 305, dtype: str

So cylinders, year and name seem to be practical categories.

In [9]:
df[['mpg', 'cylinders', 'displacement', 'weight', 'acceleration', 'model_year', 'origin']].groupby('model_year').mean()

,mpg,cylinders,displacement,weight,acceleration,origin
model_year,,,,,,
70,17.689655,6.758621,281.413793,3372.793103,12.948276,1.310345
71,21.250000,5.571429,209.750000,2995.428571,15.142857,1.428571
72,18.714286,5.821429,218.375000,3237.714286,15.125000,1.535714
73,17.100000,6.375000,256.875000,3419.025000,14.312500,1.375000
74,22.703704,5.259259,171.740741,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,3176.800000,16.050000,1.466667
76,21.573529,5.647059,197.794118,3078.735294,15.941176,1.470588
77,23.375000,5.464286,191.392857,2997.357143,15.435714,1.571429
78,24.061111,5.361111,177.805556,2861.805556,15.805556,1.611111
79,25.093103,5.827586,206.689655,3055.344828,15.813793,1.275862
80,33.696552,4.137931,115.827586,2436.655172,16.934483,2.206897
81,30.334483,4.620690,135.310345,2522.931034,16.306897,1.965517
82,31.709677,4.193548,128.870968,2453.548387,16.638710,1.645161

In [ ]:
# Group by several columns

In [11]:
df[['mpg', 'cylinders', 'displacement', 'weight', 'acceleration', 'model_year', 'origin']].groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

This is a multilevel index dataframe. For each year, it has all the existing numbers of cylinders made that year, and for each, the mean of all the other columns is provided.

In [12]:
year_cyl = df[['mpg', 'cylinders', 'displacement', 'weight', 'acceleration', 'model_year', 'origin']].groupby(['model_year', 'cylinders']).mean()
year_cyl

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

From this multilevel index dataframe you can access any particular piece. Let's start by seeing how the index look like.

In [13]:
year_cyl.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [14]:
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [16]:
year_cyl.loc[82]

                 mpg  displacement       weight  acceleration    origin
cylinders
4          32.071429    118.571429  2402.321429     16.703571  1.714286
6          28.333333    225.000000  2931.666667     16.033333  1.000000

In [17]:
# and for only the 6 cylinders for year 82 you can use the MultiIndex tuple
year_cyl.loc[(82,6)]

mpg               28.333333
displacement     225.000000
weight          2931.666667
acceleration      16.033333
origin             1.000000
Name: (82, 6), dtype: float64

In [19]:
# To get a cross section of the dataframe, e.g. all 4 cylinder data but for every year.
year_cyl.xs(key=4, level='cylinders')

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

You can also aggregate and apply different aggregation functions to different columns of a dataframe.

Let's see how to get the maximum value and the mean value for the 'mpg' column, and the mean and standard deviation for the weigth from the original dataframe

In [20]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [22]:
df.select_dtypes(include=['number']).agg(['std','mean'])

,mpg,cylinders,displacement,weight,acceleration,model_year,origin
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864

To apply different aggregation functions to different columns, you may pass a dictionary of functions by columns

In [24]:
df.agg({'mpg':['max', 'mean'],'weight':['mean','std']})

            mpg       weight
max   46.600000          NaN
mean  23.514573  2970.424623
std         NaN   846.841774