# Missing Data
You may:
- continue with missing data
- Remove the entire observation
- Replace with a sensible substitution

In [1]:
import numpy as np
import pandas as pd

NaN is a value that is not present.

It will not be equal to anything, since it is not known.

To test if a value is NaN, you shall use "is np.nan" and not "== np.nan"

In [2]:
df = pd.read_csv('../jupyter_notebooks/03-Pandas/movie_scores.csv')
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [3]:
#check where there are null and not null values.
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [4]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [5]:
# actors/actreses with not null pre movie score
df['pre_movie_score'].notnull()

0     True
1    False
2    False
3     True
4     True
Name: pre_movie_score, dtype: bool

In [6]:
# filter by that filter
df[df['pre_movie_score'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [7]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

## Three options with missing data
 1. keep the data - Just keep going, keeping in mind that you miss some values and which ones.
 2. drop the data - dropna
 3. fill the data

### Drop the data

In [8]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: Axis = 0,
    how: AnyAll | lib.NoDefault = <no_default>,
    thresh: int | lib.NoDefault = <no_default>,
    subset: IndexLabel | AnyArrayLike | None = None,
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or iterable of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "name": ["Alfred", "Batman", "Catwoman"],
    ...         "toy": [np.nan, "Batmobile", "Bullwhip"],
    ...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    ...     }
    ... )
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis="columns")
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how="all")
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=["name", "toy"])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [9]:
#drop any row having any NaN
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [13]:
# drop all rows that have less than 1 non null value
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [14]:
# if you ask for 5 non null values, Hugh gets dropped too
df.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [15]:
# rows versus column focus
#   the default behaviour: drop rows with NaN values
df.dropna(axis=0)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [16]:
#   going for columns: drop any column containing any NaN value
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

. . . because we do have a column with all values as NaN

You can drop rows that miss critical values only. Use the 'subset' parameter.

In [18]:
#Define which columns are the important ones and drop rows that miss any of them.
df.dropna(subset=['first_name', 'last_name', 'age', 'sex'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

## Fill in the data
This is the most difficult, since it involves knowing the domain in order not to bias the data

Use 'fillna()' to provide substitutes for NaN.

In [22]:
help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(
    value: Hashable | Mapping | Series | DataFrame,
    *,
    axis: Axis | None = None,
    inplace: bool = False,
    limit: int | None = None
) -> Self method of pandas.DataFrame instance
    Fill NA/NaN values with `value`.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        This is the maximum number of entries along the entire axis
        where NaNs will be filled. Must be greater than 0 if not None.

    Returns
    -------
    Series/DataFrame
        Object with missing values filled.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Notes
    -----
    For non-object dtype, ``value=None`` will use the NA value of the dtype.
    See more details in the :ref:`Filling missing data<missing_data.fillna>`
    section.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     [
    ...         [np.nan, 2, np.nan, 0],
    ...         [3, 4, np.nan, 1],
    ...         [np.nan, np.nan, np.nan, np.nan],
    ...         [np.nan, 3, np.nan, 4],
    ...     ],
    ...     columns=list("ABCD"),
    ... )
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [23]:
df.fillna('Missing')

  first_name last_name      age      sex pre_movie_score post_movie_score
0        Tom     Hanks     63.0        m             8.0             10.0
1    Missing   Missing  Missing  Missing         Missing          Missing
2       Hugh   Jackman     51.0        m         Missing          Missing
3      Oprah   Winfrey     66.0        f             6.0              8.0
4       Emma     Stone     31.0        f             7.0              9.0

In [24]:
# but it is better to fill by column, or at least by type of value
df[['pre_movie_score','post_movie_score']].fillna(0.0)

   pre_movie_score  post_movie_score
0              8.0              10.0
1              0.0               0.0
2              0.0               0.0
3              6.0               8.0
4              7.0               9.0

In [25]:
# to place it in the dataframe and make the change permanent, you have to assign it.
df['pre_movie_score'] = df['pre_movie_score'].fillna(0.0)
df['post_movie_score'] = df['post_movie_score'].fillna(0.0)
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               0.0
2       Hugh   Jackman  51.0    m              0.0               0.0
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [26]:
# But it is common to use a function (e.g. mean()) to fill the values so the filled in will not deviate the existing data
# Let's reset the dataframe and do that
df = pd.read_csv('../jupyter_notebooks/03-Pandas/movie_scores.csv')
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [27]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

In [28]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [30]:
# if you are OK with filling all numeric values with the mean, you can just use it "generically"
df.fillna(df.select_dtypes(include=['number']).mean())

  first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

Pay attention to the age now.

### Interpolation

to be used when you can trust interpolation as a good value to fill in.

Let's try with an example

In [31]:
airline_tix={'first':100,'business':np.nan,'economy-plus':50, 'economy':30}

In [32]:
ser = pd.Series(airline_tix)

In [33]:
ser

first           100.0
business          NaN
economy-plus     50.0
economy          30.0
dtype: float64

In [34]:
# set business price as interpolation between first and economy-plus
ser.interpolate()

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64