# Cross Validation

The idea is to have some means to validate that the model we train is suitable to make predictions on the kind of data we get from the domain.

The most basic concept is to split the dataset available in two: one big part to train the model and one smaller part to assess that the model predicts correctly. In this smaller part we have the actual outcome that has happened, so we can compare what the model predicts for these data points with the real outcome that did actualy happen. The key idea is that the model must never see these data points until it is asked to predict the outcome; so these data points, the test set, shall be separated immediately after cleaning the dataset and before performing any taks to build the data model. Then the model is trained on the train portion of the data set. From time to time, the model is tried out with the test set and the resulting error is used to calibrate the model further.

### Train-Test Split Procedure
0. Clean and adjust data as necessary for X and y
1. Split Data in Train/Test for both X and y
2. Fit/Train Scaler on Training X Data
3. Scale X Test Data (unless data for every feature are in the same units)
4. Create Model
5. Fit/Train Model on X Train Data
6. Evaluate Model on X Test Data (by creating predictions and comparing to Y_test)
7. Adjust Parameters as Necessary and reapeat steps 5 & 6

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../../jupyter_notebooks/DATA/Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales',axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state = 101)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler()

In [12]:
X_train = scaler.transform(X_train)

In [23]:
X_test=scaler.transform(X_test)

In [13]:
from sklearn.linear_model import Ridge

In [24]:
model = Ridge(alpha=100)

In [25]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [26]:
y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import mean_squared_error

In [28]:
mean_squared_error(y_test,y_pred)

7.341775789034128

In [29]:
model_two = Ridge(alpha=1)

In [31]:
model_two.fit(X_train,y_train)

Ridge(alpha=1)

In [32]:
y_pred_two=model_two.predict(X_test)

In [33]:
mean_squared_error(y_test,y_pred_two)

2.3190215794287514

It has performed better. But having to run the same steps over and over guessing which hyperparameter (alpha, in this case) to try next is tedious.

Besides, having adjusted model_two with knowledge of how the model has performed with X_test data, means there is some knowledge about X_test that goes in building the model. This makes X_test loose the quality for which it was constructed: evaluate the model with some data completely unknown to the model.

Let's try to overcome this by using 'train-validation-test' split. It consists on holding a second test data set to validate the model at the end, when we are happy with its performance against the test set. That is the validation set.

## Train Validation Test split technique
- still use 70% for the train data set
- split the remaining 30 percent into two sets: one test set to use as the train-test split and another one for final validation of the model. The actual % depends on how much data is available. 10% for validation is a good percentage, if the amount of data is enough to make a fair validation of the model. If not, make the validation set bigger until you fill confident.
- The process goes as the previous technique until the model is satisfactory. Then run a final prediction against the validation data set and only report on the result, do not adjust hyperparameters, nor train the model any more; just make a report on the quality of the model against the validation set.

This will be done by splitting the data set twice. The first time take the training set. The remaining data are split into validation and test sets.

In [34]:
df = pd.read_csv('../../jupyter_notebooks/DATA/Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [35]:
X = df.drop('sales',axis=1)

In [36]:
y = df['sales']

In [37]:
X_train, X_other, y_train, y_other = train_test_split(X,y,test_size=0.3,random_state = 101)

In [38]:
X_eval, X_test, y_eval, y_test = train_test_split(X_other,y_other,test_size=0.5,random_state = 101)

In [41]:
len(df)

200

In [42]:
len(X_train)

140

In [43]:
len(X_test)

30

In [44]:
len(X_eval)

30

In [45]:
len(y_train)

140

In [47]:
len(y_test)

30

In [48]:
len(y_eval)

30

In [49]:
scaler = StandardScaler()

In [50]:
scaler.fit(X_train)

StandardScaler()

In [51]:
X_train = scaler.transform(X_train)

In [52]:
X_test = scaler.transform(X_test)

In [54]:
X_eval = scaler.transform(X_eval)

In [55]:
model_one = Ridge(alpha=100)

In [56]:
model_one.fit(X_train,y_train)

Ridge(alpha=100)

In [61]:
y_eval_pred = model_one.predict(X_eval)

In [62]:
mean_squared_error(y_eval,y_eval_pred)

7.320101458823869

In [63]:
model_two = Ridge(alpha=1)

In [64]:
model_two.fit(X_train,y_train)

Ridge(alpha=1)

In [65]:
pred_eval_two = model_two.predict(X_eval)

In [66]:
mean_squared_error(y_eval,pred_eval_two)

2.3837830750569853

Let's say we are satisfied with model two.

Now is when the other data set we've reserved comes into play. We will evaluate against this unseen data set and report the model quality, but the model will not be further adjusted.

In [67]:
y_final_test_pred= model_two.predict(X_test)

In [68]:
mean_squared_error(y_test,y_final_test_pred)

2.254260083800517

This can be published/reported as the expected performance of the model against new, unseen data.

## Cross Validation
K-fold cross validation consists on:
- performing a split into train data and test data
- then the train data is split into K subsets (typical 5-10, with more data, you can use higher numbers)
- reserve one of the subsets for validation, train the model against the rest of the subsets and finally validate against the reserved one and calculate the error
- repeat reserving each of the K subsets in turns until the model has been tested against each of the K subsets. Then calculate the average of all K errors and use that to adjust the hyperparameters
- Repeat the whole K-split until you are satisfied with the resulting performance
- Use the test data to asses and report on the performance of the model.

cros_val_score in sklearn performs all this automatically.

In [69]:
df = pd.read_csv('../../jupyter_notebooks/DATA/Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [70]:
X = df.drop('sales',axis=1)

In [71]:
y = df['sales']

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=101)

In [74]:
scaler = StandardScaler()

In [75]:
scaler.fit(X_train)

StandardScaler()

In [76]:
X_train = scaler.transform(X_train)

In [77]:
X_test = scaler.transform(X_test)

In [78]:
model = Ridge(alpha=100)

In [79]:
from sklearn.model_selection import cross_val_score

Now we have to choose a scoring metric. It can be chosen from https://scikit-learn.org/stable/modules/model_evaluation.html

In [80]:
scores = cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

The scores calculated by cross_val_score are all arranged so "higher is better"; in the case of the meann squared error, is the negative of those values, so to make it signify "better" when it is "higher".

In order to be able to compare this with the performance we had before, we'll have to use the absolute value.

In [81]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

These are

In [82]:
abs(scores.mean())

np.float64(8.215396464543607)

Not very good performance. Lets make another model with alpha= 1.

In [83]:
model = Ridge(alpha=1)

In [84]:
scores = cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [85]:
scores

array([-3.15513238, -1.58086982, -5.40455562, -2.21654481, -4.36709384])

In [86]:
abs(scores.mean())

np.float64(3.344839296530695)

The model is only fitted inside cross_val_score. So in order to perform the final evaluation, we have to fit the model ourselves with the train data.

In [87]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [88]:
y_final_test_pred=model.predict(X_test)

In [89]:
mean_squared_error(y_test,y_final_test_pred)

2.3190215794287514

And this is the value you may use as reported expected performance of the model we've just trained.

## cross_validate function to perform different metrics on the fitted model performance
https://scikit-learn.org/stable/modules/model_evaluation.html

In [90]:
X = df.drop('sales',axis=1)
y = df['sales']

In [91]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [92]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [94]:
from sklearn.model_selection import cross_validate

In [95]:
model = Ridge(alpha=100)

In [96]:
scores = cross_validate(model,X_train,y_train, scoring=['neg_mean_squared_error', 'neg_mean_absolute_error'],cv=10)

In [97]:
scores

{'fit_time': array([0.00221062, 0.00209475, 0.00128794, 0.00155401, 0.00131583,
        0.00178099, 0.0037694 , 0.00203705, 0.00122976, 0.00110745]),
 'score_time': array([0.00271201, 0.00117779, 0.00137162, 0.00104284, 0.0012908 ,
        0.00156832, 0.00159788, 0.00145745, 0.00102091, 0.00095201]),
 'test_neg_mean_squared_error': array([ -6.06067062, -10.62703078,  -3.99342608,  -5.00949402,
         -9.14179955, -13.08625636,  -3.83940454,  -9.05878567,
         -9.05545685,  -5.77888211]),
 'test_neg_mean_absolute_error': array([-1.8102116 , -2.54195751, -1.46959386, -1.86276886, -2.52069737,
        -2.45999491, -1.45197069, -2.37739501, -2.44334397, -1.89979708])}

In [98]:
scores = pd.DataFrame(scores)

In [99]:
scores

,fit_time,score_time,test_neg_mean_squared_error,test_neg_mean_absolute_error
0,0.002211,0.002712,-6.060671,-1.810212
1,0.002095,0.001178,-10.627031,-2.541958
2,0.001288,0.001372,-3.993426,-1.469594
3,0.001554,0.001043,-5.009494,-1.862769
4,0.001316,0.001291,-9.141800,-2.520697
5,0.001781,0.001568,-13.086256,-2.459995
6,0.003769,0.001598,-3.839405,-1.451971
7,0.002037,0.001457,-9.058786,-2.377395
8,0.001230,0.001021,-9.055457,-2.443344
9,0.001107,0.000952,-5.778882,-1.899797

In [100]:
scores.mean()

fit_time                        0.001839
score_time                      0.001419
test_neg_mean_squared_error    -7.565121
test_neg_mean_absolute_error   -2.083773
dtype: float64

In [101]:
model = Ridge(alpha=1)

In [102]:
scores = cross_validate(model,X_train,y_train, scoring=['neg_mean_squared_error', 'neg_mean_absolute_error'],cv=10)

In [103]:
scores = pd.DataFrame(scores)

In [104]:
scores.mean()

fit_time                        0.001913
score_time                      0.001586
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [105]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [106]:
y_final_pred=model.predict(X_test)

In [107]:
mean_squared_error(y_test,y_final_pred)

2.3190215794287514

This is the performance value that can be reported as the expected performance of the model with new, unseen data.