# Pandas Input and Output

In [1]:
import pandas as pd

## CSV files

In [2]:
pwd

'C:\\D\\GitRepos\\Python\\python4ML_DS\\resources\\Notes'

In [3]:
ls

 El volumen de la unidad C es OSDisk
 El nÃºmero de serie del volumen es: E63C-6C45

 Directorio de C:\D\GitRepos\Python\python4ML_DS\resources\Notes

13/04/2026  10:24    <DIR>          .
13/03/2026  01:13    <DIR>          ..
13/04/2026  10:16    <DIR>          .ipynb_checkpoints
10/04/2026  20:43            40.848 CombiningDataFrames.ipynb
10/04/2026  21:27            31.301 DealingWithTimeAndDate.ipynb
23/03/2026  13:17             3.727 DependencyVerification.ipynb
09/04/2026  23:13            85.238 GroupBy.ipynb
09/04/2026  20:55            61.860 MissingData.ipynb
23/03/2026  17:30            15.474 Numpy-I.ipynb
23/03/2026  17:30            20.676 Numpy-II.ipynb
25/03/2026  22:18           163.597 Pandas.ipynb
07/04/2026  20:13           108.819 Pandas_ConditionalFiltering.ipynb
13/04/2026  10:24             2.082 PandasInputOutput.ipynb
18/03/2026  17:37             1.442 Python4ML_DS.txt
19/03/2026  00:39            27.491 PythonCrashCourse.ipynb
10/04/2026  12:47            10.272 TextManipulation.ipynb
07/04/2026  21:31            39.048 UsefulMethods_MultipleColumns.ipynb
07/04/2026  21:11            30.145 UsefulMethods_SingleColumn.ipynb
08/04/2026  23:51            85.849 UsefulMethods_StatisticalAndSorting.ipynb
              16 archivos        727.869 bytes
               3 dirs  124.710.072.320 bytes libres

In [4]:
# Outside jupiter notebooks, you can use the os package
import os
os.getcwd()

'C:\\D\\GitRepos\\Python\\python4ML_DS\\resources\\Notes'

In [5]:
os.listdir()

['.ipynb_checkpoints',
 'CombiningDataFrames.ipynb',
 'DealingWithTimeAndDate.ipynb',
 'DependencyVerification.ipynb',
 'GroupBy.ipynb',
 'MissingData.ipynb',
 'Numpy-I.ipynb',
 'Numpy-II.ipynb',
 'Pandas.ipynb',
 'PandasInputOutput.ipynb',
 'Pandas_ConditionalFiltering.ipynb',
 'Python4ML_DS.txt',
 'PythonCrashCourse.ipynb',
 'TextManipulation.ipynb',
 'UsefulMethods_MultipleColumns.ipynb',
 'UsefulMethods_SingleColumn.ipynb',
 'UsefulMethods_StatisticalAndSorting.ipynb']

In [6]:
df = pd.read_csv('../jupyter_notebooks/03-Pandas/example.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
# Make the 1st row be a data row instead of header
df = pd.read_csv('../jupyter_notebooks/03-Pandas/example.csv', header=None)
df

    0   1   2   3
0   a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [8]:
# Make the first column be the index
df = pd.read_csv('../jupyter_notebooks/03-Pandas/example.csv',index_col=0)
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [10]:
# Save current dataframe
df.to_csv('../Notes/csv_saving_example.csv',index=True)

## HTML tables

Not always is possible to read html tables into dataframes. For starters it has to be in HTML format.

In [16]:
#explore world population page at Wikipedia
url='C:/Users/mvgarcia/Downloads/WorldPopulation.htm'

In [17]:
tables=pd.read_html(url)
tables

[  Population (in billions)     1   1.1     2   2.1     3   3.1     4   4.1  \
 0                     Year  1804  1804  1927  1927  1960  1960  1974  1974
 1            Years elapsed     —   123   123    33    33    14    14    13

       5  ...     6   6.1     7   7.1     8   8.1     9   9.1    10  10.1
 0  1987  ...  1999  1999  2011  2011  2022  2022  2037  2037  2057  2057
 1    13  ...    12    12    12    11    11    15    15    20    20     —

 [2 rows x 21 columns],
                                Region  2022 (percent)  2030 (percent)  \
 0                  Sub-Saharan Africa  1,152 (14.51%)  1,401 (16.46%)
 1    Northern Africa and Western Asia     549 (6.91%)     617 (7.25%)
 2      Central Asia and Southern Asia  2,075 (26.13%)  2,248 (26.41%)
 3  Eastern Asia and Southeastern Asia  2,342 (29.49%)  2,372 (27.87%)
 4         Europe and Northern America  1,120 (14.10%)  1,129 (13.26%)
 5     Latin America and the Caribbean     658 (8.29%)     695 (8.17%)
 6           Australia and New Zealand      31 (0.39%)      34 (0.40%)
 7                             Oceania      14 (0.18%)      15 (0.18%)
 8                               World            7942            8512

    2050 (percent)
 0  2,094 (21.62%)
 1     771 (7.96%)
 2  2,575 (26.58%)
 3  2,317 (23.92%)
 4  1,125 (11.61%)
 5     749 (7.73%)
 6      38 (0.39%)
 7      20 (0.21%)
 8            9687  ,
                      Region Density (inhabitants/km2) Population (millions)  \
 0                      Asia                     104.1                  4641
 1                    Africa                      44.4                  1340
 2                    Europe                      73.4                   747
 3             Latin America                      24.1                   653
 4  Northern America[note 1]                      14.9                   368
 5                   Oceania                         5                    42
 6                Antarctica                        ~0             0.004[90]

                                Most populous country  \
 0                              1,439,090,595 – India
 1                            0,211,401,000 – Nigeria
 2  0,146,171,000 – Russia, approx. 110 million in...
 3                             0,214,103,000 – Brazil
 4                      0,332,909,000 – United States
 5                          0,025,917,000 – Australia
 6                                        N/A[note 2]

               Most populous city (metropolitan area)
 0  13,515,000 – Tokyo Metropolis (37,400,000 – Gr...
 1    09,500,000 – Cairo (20,076,000 – Greater Cairo)
 2  13,200,000 – Moscow (20,004,000 – Moscow metro...
 3  12,252,000 – São Paulo City (21,650,000 – São ...
 4  08,804,000 – New York City (23,582,649 – New Y...
 5                                05,367,000 – Sydney
 6                       00,001,258 – McMurdo Station  ,
   Country / Dependency  Population % of world         Date  \
 0                India  1425775850      17.3%  14 Apr 2023
 1                China  1409670000      17.1%  17 Jan 2024
 2        United States   339176896      4.12%  12 Apr 2026
 3            Indonesia   278696200      3.38%   1 Jul 2023
 4             Pakistan   229488994      2.78%   1 Jul 2022
 5               Brazil   220544333      2.68%  12 Apr 2026
 6              Nigeria   216746934      2.63%   1 Jul 2022
 7           Bangladesh   168220000      2.04%   1 Jul 2020
 8               Russia   147190000      1.79%   1 Oct 2021
 9               Mexico   128271248      1.56%  31 Mar 2022

   Source (official or from the United Nations)
 0                            UN projection[93]
 1                 National annual estimate[94]
 2                National population clock[95]
 3                 National annual estimate[96]
 4                            UN projection[97]
 5                National population clock[98]
 6                            UN projection[97]
 7               Annual Population Estimate[99]
 8         2021 preliminary census results[100]
 9                                          NaN  ,
                                                     #  \
 0                                                   1
 1                                                   2
 2                                                   3
 3                                                   4
 4                                                   5
 5                                                   6
 6                                                   7
 7                                                   8
 8                                                   9
 9                                                  10
 10                                                NaN
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...

                               Most populous countries  \
 0                                            China[B]
 1                                               India
 2                                       United States
 3                                           Indonesia
 4                                            Pakistan
 5                                              Brazil
 6                                             Nigeria
 7                                          Bangladesh
 8                                              Russia
 9                                              Mexico
 10                                        World total
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...

                                                  2000  \
 0                                                1270
 1                                                1053
 2                                                 283
 3                                                 212
 4                                                 136
 5                                                 176
 6                                                 123
 7                                                 131
 8                                                 146
 9                                                 103
 10                                               6127
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...

                                                  2015  \
 0                                                1376
 1                                                1311
 2                                                 322
 3                                                 258
 4                                                 208
 5                                                 206
 6                                                 182
 7                                                 161
 8                                                 146
 9                                                 127
 10                                               7349
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...

                                               2030[A]  \
 0                                                1416
 1                                                1528
 2                                                 356
 3                                                 295
 4                                                 245
 5                                                 228
 6                                                 263
 7                                                 186
 8                                                 149
 9                                                 148
 10                                               8501
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...

    Y axisX axis0300600900120015001800200020152030ChinaIndiaUnited StatesIndonesiaPakistanBrazilNigeriaBangladeshRussiaMexicoTen most populous countries raw data
 0   Y axisX axis0300600900120015001800200020152030...
 1   Y axisX axis0300600900120015001800200020152030...
 2   Y axisX axis0300600900120015001800200020152030...
 3   Y axisX axis0300600900120015001800200020152030...
 4   Y axisX axis0300600900120015001800200020152030...
 5   Y axisX axis0300600900120015001800200020152030...
 6   Y axisX axis0300600900120015001800200020152030...
 7   Y axisX axis0300600900120015001800200020152030...
 8   Y axisX axis0300600900120015001800200020152030...
 9   Y axisX axis0300600900120015001800200020152030...
 10  Y axisX axis0300600900120015001800200020152030...
 11  Notes: ^ 2030 = Medium variant. ^ China exclud...                                                                                                             ,
    Rank                 Country  Population  Area (km2)  Density (pop/km2)
 0     1               Singapore     5921231         719               8235
 1     2              Bangladesh   165650475      148460               1116
 2     3  Palestine[note 3][103]     5223000        6025                867
 3     4          Taiwan[note 4]    23580712       35980                655
 4     5             South Korea    51844834       99720                520
 5     6                 Lebanon     5296814       10400                509
 6     7                  Rwanda    13173730       26338                500
 7     8                 Burundi    12696478       27830                456
 8     9                  Israel     9402617       21937                429
 9    10                   India  1389637446     3287263                423,
    Rank         Country  Population  Area (km2)  Density (pop/km2)  \
 0     1           India  1389637446     3287263                423
 1     2        Pakistan   242923845      796095                305
 2     3      Bangladesh   165650475      148460               1116
 3     4           Japan   124214766      377915                329
 4     5     Philippines   114597229      300000                382
 5     6         Vietnam   103808319      331210                313
 6     7  United Kingdom    67791400      243610                278
 7     8     South Korea    51844834       99720                520
 8     9          Taiwan    23580712       35980                655
 9    10       Sri Lanka    23187516       65610                353

   Population trend[citation needed]
 0                           Growing
 1                   Rapidly growing
 2                           Growing
 3                    Declining[104]
 4                           Growing
 5                           Growing
 6                           Growing
 7                            Steady
 8                            Steady
 9                           Growing  ,
     Year  Population Yearly growth           Density (pop/km2)
     Year  Population             %    Number Density (pop/km2)
 0   1951  2543130380         1.75%  43808223                17
 1   1952  2590270899         1.85%  47140519                17
 2   1953  2640278797         1.93%  50007898                18
 3   1954  2691979339         1.96%  51700542                18
 4   1955  2746072141         2.01%  54092802                18
 ..   ...         ...           ...       ...               ...
 68  2019  7764951032         1.06%  81161204                52
 69  2020  7840952880         0.98%  76001848                53
 70  2021  7909295151         0.87%  68342271                53
 71  2022  7975105156         0.83%  65810005                54
 72  2023  8045311447         0.88%  70206291                54

 [73 rows x 5 columns],
                      Region  1500  1600  1700  1750  1800  1850  1900  1950  \
 0                     World   585   660   710   791   978  1262  1650  2521
 1                    Africa    86   114   106   106   107   111   133   221
 2                      Asia   282   350   411   502   635   809   947  1402
 3                    Europe   168   170   178   190   203   276   408   547
 4     Latin America[Note 1]    40    20    10    16    24    38    74   167
 5  Northern America[Note 1]     6     3     2     2     7    26    82   172
 6                   Oceania     3     3     3     2     2     2     6    13

    1999  2008  2010  2012  2050  2150
 0  6008  6707  6896  7052  9725  9746
 1   783   973  1022  1052  2478  2308
 2  3700  4054  4164  4250  5267  5561
 3   675   732   738   740   734   517
 4   508   577   590   603   784   912
 5   312   337   345   351   433   398
 6    30    34    37    38    57    51  ,
                      Region  1500  1600  1700  1750  1800  1850  1900  1950  \
 0                    Africa  14.7  17.3  14.9  13.4  10.9   8.8   8.1   8.8
 1                      Asia  48.2  53.0  57.9  63.5  64.9  64.1  57.4  55.6
 2                    Europe  28.7  25.8  25.1  20.6  20.8  21.9  24.7  21.7
 3     Latin America[Note 1]   6.8   3.0   1.4   2.0   2.5   3.0   4.5   6.6
 4  Northern America[Note 1]   1.0   0.5   0.3   0.3   0.7   2.1   5.0   6.8
 5                   Oceania   0.5   0.5   0.4   0.3   0.2   0.2   0.4   0.5

    1999  2008  2010  2012  2050  2150
 0  13.0  14.5  14.8  15.2  25.5  23.7
 1  61.6  60.4  60.4  60.3  54.2  57.1
 2  11.2  10.9  10.7  10.5   7.6   5.3
 3   8.5   8.6   8.6   8.6   8.1   9.4
 4   5.2   5.0   5.0   5.0   4.5   4.1
 5   0.5   0.5   0.5   0.5   0.6   0.5  ,
          Year    World  Africa    Asia  Europe  \
 0   70,000 BC  < 0.015     NaN     NaN     NaN
 1   10,000 BC        4     NaN     NaN     NaN
 2     8000 BC        5     NaN     NaN     NaN
 3     6500 BC        5     NaN     NaN     NaN
 4     5000 BC        5     NaN     NaN     NaN
 5     4000 BC        7     NaN     NaN     NaN
 6     3000 BC       14     NaN     NaN     NaN
 7     2000 BC       27     NaN     NaN     NaN
 8     1000 BC       50     7.0    33.0     9.0
 9      500 BC      100    14.0    66.0    16.0
 10       AD 1      200    23.0   141.0    28.0
 11       1000      400    70.0   269.0    50.0
 12       1500      458    86.0   243.0    84.0
 13       1600      580   114.0   339.0   111.0
 14       1700      682   106.0   436.0   125.0
 15       1750      791   106.0   502.0   163.0
 16       1800     1000   107.0   656.0   203.0
 17       1850     1262   111.0   809.0   276.0
 18       1900     1650   133.0   947.0   408.0
 19       1950     2525   229.0  1394.0   549.0
 20       1955     2758   254.0  1534.0   577.0
 21       1960     3018   285.0  1687.0   606.0
 22       1965     3322   322.0  1875.0   635.0
 23       1970     3682   366.0  2120.0   657.0
 24       1975     4061   416.0  2378.0   677.0
 25       1980     4440   478.0  2626.0   694.0
 26       1985     4853   550.0  2897.0   708.0
 27       1990     5310   632.0  3202.0   721.0
 28       1995     5735   720.0  3475.0   728.0
 29       2000     6127   814.0  3714.0   726.0
 30       2005     6520   920.0  3945.0   729.0
 31       2010     6930  1044.0  4170.0   735.0
 32       2015     7349  1186.0  4393.0   738.0

     Latin America & Carib.[Note 1]  North America [Note 1]  Oceania  \
 0                              NaN                     NaN      NaN
 1                              NaN                     NaN      NaN
 2                              NaN                     NaN      NaN
 3                              NaN                     NaN      NaN
 4                              NaN                     NaN      NaN
 5                              NaN                     NaN      NaN
 6                              NaN                     NaN      NaN
 7                              NaN                     NaN      NaN
 8                              NaN                     NaN      NaN
 9                              NaN                     NaN      NaN
 10                             NaN                     NaN      NaN
 11                             8.0                     1.0      2.0
 12                            39.0                     3.0      3.0
 13                            10.0                     3.0      3.0
 14                            10.0                     2.0      3.0
 15                            16.0                     2.0      2.0
 16                            24.0                     7.0      3.0
 17                            38.0                    26.0      2.0
 18                            74.0                    82.0      6.0
 19                           169.0                   172.0     12.7
 20                           193.0                   187.0     14.2
 21                           221.0                   204.0     15.8
 22                           254.0                   219.0     17.5
 23                           288.0                   231.0     19.7
 24                           326.0                   242.0     21.5
 25                           365.0                   254.0     23.0
 26                           406.0                   267.0     24.9
 27                           447.0                   281.0     27.0
 28                           487.0                   296.0     29.1
 29                           527.0                   314.0     31.1
 30                           564.0                   329.0     33.4
 31                           600.0                   344.0     36.4
 32                           634.0                   358.0     39.3

                 Notes
 0               [121]
 1               [122]
 2                 NaN
 3                 NaN
 4                 NaN
 5                 NaN
 6                 NaN
 7                 NaN
 8   [citation needed]
 9                 NaN
 10                NaN
 11                NaN
 12                NaN
 13                NaN
 14                NaN
 15                NaN
 16                NaN
 17                NaN
 18                NaN
 19              [123]
 20                NaN
 21                NaN
 22                NaN
 23                NaN
 24                NaN
 25                NaN
 26                NaN
 27                NaN
 28                NaN
 29                NaN
 30                NaN
 31                NaN
 32                NaN  ,
     0                                                  1
 0 NaN  This section needs additional citations for ve...,
    Year  UN est. (millions) Difference  USCB est. (millions) Difference.1
 0  2005                6542          –                  6473            –
 1  2010                6957        415                  6866          393
 2  2015                7380        423                  7256          390
 3  2020                7795        415                  7643          380
 4  2025                8184        390                  8007          363
 5  2030                8549        364                  8341          334
 6  2035                8888        339                  8646          306
 7  2040                9199        311                  8926          280
 8  2045                9482        283                  9180          254
 9  2050                9735        253                  9408          228,
    Year  World           Asia         Africa       Europe  \
 0  2000   6144  3,741 (60.9%)    811 (13.2%)  726 (11.8%)
 1  2024   8160  4,810 (58.9%)  1,520 (18.6%)   745 (9.1%)
 2  2050   9660  5,280 (54.7%)  2,470 (25.6%)   703 (7.3%)
 3  2075  10250  5,100 (49.8%)  3,290 (32.1%)   636 (6.2%)
 4  2100  10180  4,610 (45.3%)  3,810 (37.4%)   592 (5.8%)

   Latin Am./ Caribbean Northern America    Oceania
 0           522 (8.5%)       312 (5.1%)  31 (0.5%)
 1           663 (8.1%)       385 (4.7%)  46 (0.6%)
 2           730 (7.6%)       426 (4.4%)  57 (0.6%)
 3           698 (6.8%)       452 (4.4%)  66 (0.6%)
 4           613 (6.0%)       475 (4.7%)  73 (0.7%)  ,
   Population (in billions)   0.5  0.5.1     1   1.1     2   2.1     4   4.1  \
 0                     Year  1500   1500  1804  1804  1927  1927  1974  1974
 1            Years elapsed     —    304   304   123   123    47    47    48

       8   8.1 16 16.1
 0  2022  2022  —    —
 1    48     —  —    —  ,
   Population (in billions) 0.375  0.375.1  0.75  0.75.1   1.5  1.5.1     3  \

In [18]:
len(tables)

26

In [19]:
tables[0]

,Population (in billions),1,1.1,2,2.1,3,3.1,4,4.1,5,...,6,6.1,7,7.1,8,8.1,9,9.1,10,10.1
0,Year,1804,1804,1927,1927,1960,1960,1974,1974,1987,...,1999,1999,2011,2011,2022,2022,2037,2037,2057,2057
1,Years elapsed,—,123,123,33,33,14,14,13,13,...,12,12,12,11,11,15,15,20,20,—

In [20]:
tables[1]

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [21]:
tables[2]

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,439,090,595 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[90],N/A[note 2],"00,001,258 – McMurdo Station"

In [24]:
tables[3]

,Country / Dependency,Population,% of world,Date,Source (official or from the United Nations)
0,India,1425775850,17.3%,14 Apr 2023,UN projection[93]
1,China,1409670000,17.1%,17 Jan 2024,National annual estimate[94]
2,United States,339176896,4.12%,12 Apr 2026,National population clock[95]
3,Indonesia,278696200,3.38%,1 Jul 2023,National annual estimate[96]
4,Pakistan,229488994,2.78%,1 Jul 2022,UN projection[97]
5,Brazil,220544333,2.68%,12 Apr 2026,National population clock[98]
6,Nigeria,216746934,2.63%,1 Jul 2022,UN projection[97]
7,Bangladesh,168220000,2.04%,1 Jul 2020,Annual Population Estimate[99]
8,Russia,147190000,1.79%,1 Oct 2021,2021 preliminary census results[100]
9,Mexico,128271248,1.56%,31 Mar 2022,NaN

In [25]:
tables[4]

,#,Most populous countries,2000,2015,2030[A],Y axisX axis0300600900120015001800200020152030ChinaIndiaUnited StatesIndonesiaPakistanBrazilNigeriaBangladeshRussiaMexicoTen most populous countries raw data
0,1,China[B],1270,1376,1416,Y axisX axis0300600900120015001800200020152030...
1,2,India,1053,1311,1528,Y axisX axis0300600900120015001800200020152030...
2,3,United States,283,322,356,Y axisX axis0300600900120015001800200020152030...
3,4,Indonesia,212,258,295,Y axisX axis0300600900120015001800200020152030...
4,5,Pakistan,136,208,245,Y axisX axis0300600900120015001800200020152030...
5,6,Brazil,176,206,228,Y axisX axis0300600900120015001800200020152030...
6,7,Nigeria,123,182,263,Y axisX axis0300600900120015001800200020152030...
7,8,Bangladesh,131,161,186,Y axisX axis0300600900120015001800200020152030...
8,9,Russia,146,146,149,Y axisX axis0300600900120015001800200020152030...
9,10,Mexico,103,127,148,Y axisX axis0300600900120015001800200020152030...
10,NaN,World total,6127,7349,8501,Y axisX axis0300600900120015001800200020152030...
11,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [27]:
world_topten=tables[4]
world_topten.columns.values

<StringArray>
[                                                                                                                                                            '#',
                                                                                                                                       'Most populous countries',
                                                                                                                                                          '2000',
                                                                                                                                                          '2015',
                                                                                                                                                       '2030[A]',
 'Y axisX axis0300600900120015001800200020152030ChinaIndiaUnited StatesIndonesiaPakistanBrazilNigeriaBangladeshRussiaMexicoTen most populous countries raw data']
Length: 6, dtype: str

In [28]:
world_topten=world_topten.drop(['#','Y axisX axis0300600900120015001800200020152030ChinaIndiaUnited StatesIndonesiaPakistanBrazilNigeriaBangladeshRussiaMexicoTen most populous countries raw data'],axis=1)
world_topten

,Most populous countries,2000,2015,2030[A]
0,China[B],1270,1376,1416
1,India,1053,1311,1528
2,United States,283,322,356
3,Indonesia,212,258,295
4,Pakistan,136,208,245
5,Brazil,176,206,228
6,Nigeria,123,182,263
7,Bangladesh,131,161,186
8,Russia,146,146,149
9,Mexico,103,127,148
10,World total,6127,7349,8501
11,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [29]:
world_topten = world_topten.drop(11,axis=0)
world_topten

   Most populous countries  2000  2015 2030[A]
0                 China[B]  1270  1376    1416
1                    India  1053  1311    1528
2            United States   283   322     356
3                Indonesia   212   258     295
4                 Pakistan   136   208     245
5                   Brazil   176   206     228
6                  Nigeria   123   182     263
7               Bangladesh   131   161     186
8                   Russia   146   146     149
9                   Mexico   103   127     148
10             World total  6127  7349    8501

In [30]:
world_topten.columns=['Country','2000','2015','2030 Estimate']
world_topten

          Country  2000  2015 2030 Estimate
0        China[B]  1270  1376          1416
1           India  1053  1311          1528
2   United States   283   322           356
3       Indonesia   212   258           295
4        Pakistan   136   208           245
5          Brazil   176   206           228
6         Nigeria   123   182           263
7      Bangladesh   131   161           186
8          Russia   146   146           149
9          Mexico   103   127           148
10    World total  6127  7349          8501

In [32]:
tables[6]

,Rank,Country,Population,Area (km2),Density (pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

In [33]:
most_populated = tables[6]
most_populated

,Rank,Country,Population,Area (km2),Density (pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

In [36]:
most_populated = most_populated.set_index('Rank')

In [37]:
most_populated

,Country,Population,Area (km2),Density (pop/km2),Population trend[citation needed]
Rank,,,,,
1,India,1389637446,3287263,423,Growing
2,Pakistan,242923845,796095,305,Rapidly growing
3,Bangladesh,165650475,148460,1116,Growing
4,Japan,124214766,377915,329,Declining[104]
5,Philippines,114597229,300000,382,Growing
6,Vietnam,103808319,331210,313,Growing
7,United Kingdom,67791400,243610,278,Growing
8,South Korea,51844834,99720,520,Steady
9,Taiwan,23580712,35980,655,Steady
10,Sri Lanka,23187516,65610,353,Growing

In [38]:
most_populated.columns.values

<StringArray>
[                          'Country',                        'Population',
                        'Area (km2)',                 'Density (pop/km2)',
 'Population trend[citation needed]']
Length: 5, dtype: str

In [39]:
most_populated.columns = ['Country', 'Population', 'Area (km2)', 'Density (pop/km2)', 'Population trend']

In [40]:
most_populated

,Country,Population,Area (km2),Density (pop/km2),Population trend
Rank,,,,,
1,India,1389637446,3287263,423,Growing
2,Pakistan,242923845,796095,305,Rapidly growing
3,Bangladesh,165650475,148460,1116,Growing
4,Japan,124214766,377915,329,Declining[104]
5,Philippines,114597229,300000,382,Growing
6,Vietnam,103808319,331210,313,Growing
7,United Kingdom,67791400,243610,278,Growing
8,South Korea,51844834,99720,520,Steady
9,Taiwan,23580712,35980,655,Steady
10,Sri Lanka,23187516,65610,353,Growing

In [46]:
most_populated.loc[7,'Country'] = 'U.K.'

In [45]:
most_populated

          Country  Population  Area (km2)  Density (pop/km2) Population trend
Rank
1           India  1389637446     3287263                423          Growing
2        Pakistan   242923845      796095                305  Rapidly growing
3      Bangladesh   165650475      148460               1116          Growing
4           Japan   124214766      377915                329   Declining[104]
5     Philippines   114597229      300000                382          Growing
6         Vietnam   103808319      331210                313          Growing
7             U.K    67791400      243610                278          Growing
8     South Korea    51844834       99720                520           Steady
9          Taiwan    23580712       35980                655           Steady
10      Sri Lanka    23187516       65610                353          Growing

In [49]:
most_populated['Population trend']=most_populated['Population trend'].map({'Growing':'↑','Rapidly growing':'↑↑↑','Declining[104]':'↓','Steady':'↔'})
most_populated

          Country  Population  Area (km2)  Density (pop/km2) Population trend
Rank
1           India  1389637446     3287263                423                ↑
2        Pakistan   242923845      796095                305              ↑↑↑
3      Bangladesh   165650475      148460               1116                ↑
4           Japan   124214766      377915                329                ↓
5     Philippines   114597229      300000                382                ↑
6         Vietnam   103808319      331210                313                ↑
7            U.K.    67791400      243610                278              NaN
8     South Korea    51844834       99720                520                ↔
9          Taiwan    23580712       35980                655                ↔
10      Sri Lanka    23187516       65610                353                ↑

### Save dataframe to a HTML file.

In [ ]:
world_topten.to_html('../Notes/csv_saving_example.csv',index=True)

In [51]:
most_populated.to_html('../Notes/csv_Other_saving_example.csv', index=True)

## Excel files

In [52]:
df = pd.read_excel('../jupyter_notebooks/03-Pandas/my_excel_file.xlsx', sheet_name='First_Sheet')

In [53]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [54]:
wb= pd.ExcelFile('../jupyter_notebooks/03-Pandas/my_excel_file.xlsx')

In [55]:
wb.sheet_names

['First_Sheet']

In [56]:
# to deal with large workbooks with many sheets: sheet_name=None
excel_sheet_dict = pd.read_excel('../jupyter_notebooks/03-Pandas/my_excel_file.xlsx', sheet_name=None)
type(excel_sheet_dict)

dict

In [69]:
#  Then you have all the keys in excel_sheet_dict.keys(), you can transform that to a list and then access them by index.
#   So the first sheet would be:
excel_sheet_dict[list(excel_sheet_dict.keys())[0]]

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [70]:
single_sheet = excel_sheet_dict[list(excel_sheet_dict.keys())[0]]

In [71]:
single_sheet.to_excel('../Notes/excel_saving_example.xlsx', sheet_name='First_Sheet', index = True)

## SQL Databases

In [76]:
from sqlalchemy import create_engine
import numpy as np

In [73]:
temp_db = create_engine('sqlite:///:memory:')

In [77]:
df = pd.DataFrame(data=np.random.randint(low=0,high=100,size=(4,4)),columns=['a','b','c','d'])
df

    a   b   c   d
0  82  33  91  73
1  60  11  26  54
2  87  40  14  24
3  88  89  80  55

In [78]:
df.to_sql(name='new_table', con=temp_db)

4

In [79]:
new_df= pd.read_sql(sql='new_table',con=temp_db)
new_df

   index   a   b   c   d
0      0  82  33  91  73
1      1  60  11  26  54
2      2  87  40  14  24
3      3  88  89  80  55

In [81]:
short_table = pd.read_sql_query(sql="SELECT a,c FROM new_table", con=temp_db)
short_table

    a   c
0  82  91
1  60  26
2  87  14
3  88  80