# Pandas Pivot Tables
Tehy reorganise information in a DataFrame, they do not find out or calculate new information: they just reorgainise, focus, and, maybe, drop some information.

It only makes sense to pivot DataFrames with repeated values over each column of interest.

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../jupyter_notebooks/03-Pandas/Sales_Funnel_CRM.csv')

In [5]:
df

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
5,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Analytics,300,2800000,Under Review
6,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Prediction,150,700000,Presented
7,1216870,Microsoft,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
8,2200450,Walmart,Will Grates,Edward Thorp,Analytics,150,2450000,Lost
9,405886,Apple,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
10,470248,Exxon Mobile,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
11,698032,ATT,Cindy Phoner,Claude Shannon,Tracking,150,350000,Under Review
12,698032,ATT,Cindy Phoner,Claude Shannon,Prediction,150,700000,Presented
13,902797,CVS Health,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
14,2046943,Salesforce,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
15,2169499,Cisco,Emma Gordian,Claude Shannon,Analytics,300,4550000,Lost
16,2169499,Cisco,Emma Gordian,Claude Shannon,GPS Positioning,300,350000,Presented

In [8]:
# How many licenses of each type did Google purchase?
licenses =df[['Company','Product','Licenses']]
licenses

         Company          Product  Licenses
0         Google        Analytics       150
1         Google       Prediction       150
2         Google         Tracking       300
3           BOBO        Analytics       150
4           IKEA        Analytics       300
5     Tesla Inc.        Analytics       300
6     Tesla Inc.       Prediction       150
7      Microsoft         Tracking       300
8        Walmart        Analytics       150
9          Apple        Analytics       300
10  Exxon Mobile        Analytics       150
11           ATT         Tracking       150
12           ATT       Prediction       150
13    CVS Health         Tracking       450
14    Salesforce        Analytics       750
15         Cisco        Analytics       300
16         Cisco  GPS Positioning       300

In [7]:
pd.pivot(data=licenses, index='Company',columns='Product',values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [9]:
#How much have we sold per company
pd.pivot_table(df,index="Company",aggfunc='sum')

,Account Manager,Account Number,Contact,Licenses,Product,Sale Price,Status
Company,,,,,,,
Google,Edward ThorpEdward ThorpEdward Thorp,6370194,Larry PagerLarry PagerLarry Pager,600,AnalyticsPredictionTracking,3150000,PresentedPresentedUnder Review
ATT,Claude ShannonClaude Shannon,1396064,Cindy PhonerCindy Phoner,300,TrackingPrediction,1050000,Under ReviewPresented
Apple,Claude Shannon,405886,Cindy Phoner,300,Analytics,4550000,Won
BOBO,Edward Thorp,2192650,Larry Pager,150,Analytics,2450000,Lost
CVS Health,Claude Shannon,902797,Emma Gordian,450,Tracking,490000,Won
Cisco,Claude ShannonClaude Shannon,4338998,Emma GordianEmma Gordian,600,AnalyticsGPS Positioning,4900000,LostPresented
Exxon Mobile,Claude Shannon,470248,Cindy Phoner,150,Analytics,2100000,Presented
IKEA,Edward Thorp,420496,Elon Tusk,300,Analytics,4550000,Won
Microsoft,Edward Thorp,1216870,Will Grates,300,Tracking,350000,Under Review
Salesforce,Claude Shannon,2046943,Emma Gordian,750,Analytics,7000000,Won
Tesla Inc.,Edward ThorpEdward Thorp,1273370,Elon TuskElon Tusk,450,AnalyticsPrediction,3500000,Under ReviewPresented
Walmart,Edward Thorp,2200450,Will Grates,150,Analytics,2450000,Lost

In [10]:
#You can achieve the same with groupby
df.groupby('Company').sum()

,Account Number,Contact,Account Manager,Product,Licenses,Sale Price,Status
Company,,,,,,,
Google,6370194,Larry PagerLarry PagerLarry Pager,Edward ThorpEdward ThorpEdward Thorp,AnalyticsPredictionTracking,600,3150000,PresentedPresentedUnder Review
ATT,1396064,Cindy PhonerCindy Phoner,Claude ShannonClaude Shannon,TrackingPrediction,300,1050000,Under ReviewPresented
Apple,405886,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
BOBO,2192650,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
CVS Health,902797,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
Cisco,4338998,Emma GordianEmma Gordian,Claude ShannonClaude Shannon,AnalyticsGPS Positioning,600,4900000,LostPresented
Exxon Mobile,470248,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
IKEA,420496,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
Microsoft,1216870,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
Salesforce,2046943,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
Tesla Inc.,1273370,Elon TuskElon Tusk,Edward ThorpEdward Thorp,AnalyticsPrediction,450,3500000,Under ReviewPresented
Walmart,2200450,Will Grates,Edward Thorp,Analytics,150,2450000,Lost

In [11]:
# To limit the columns that are operated, you may use values argument
pd.pivot_table(df,index="Company",aggfunc='sum',values=['Licenses','Sale Price'])

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [12]:
pd.pivot_table(df,index=['Account Manager','Contact'],values=['Sale Price'],aggfunc='sum')

                              Sale Price
Account Manager Contact
Claude Shannon  Cindy Phoner     7700000
                Emma Gordian    12390000
Edward Thorp    Elon Tusk        8050000
                Larry Pager      5600000
                Will Grates      2800000

In [13]:
# Add in information about products
pd.pivot_table(df,index=['Account Manager','Contact'],values=['Sale Price'],columns=['Product'],aggfunc='sum')

                              Sale Price
Product                        Analytics GPS Positioning Prediction  Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner   6650000.0             NaN   700000.0  350000.0
                Emma Gordian  11550000.0        350000.0        NaN  490000.0
Edward Thorp    Elon Tusk      7350000.0             NaN   700000.0       NaN
                Larry Pager    4550000.0             NaN   700000.0  350000.0
                Will Grates    2450000.0             NaN        NaN  350000.0

In [14]:
# do something about the NaN values
pd.pivot_table(df,index=['Account Manager','Contact'],values=['Sale Price'],columns=['Product'],aggfunc='sum',fill_value=0)

                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

In [15]:
# if you use numpy functions for the aggregation, you can specify more than one
pd.pivot_table(df,index=['Account Manager','Contact'],values=['Sale Price'],columns=['Product'],aggfunc=[np.sum,np.mean],fill_value=0)

                                    sum                                      \
                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

                                   mean
                             Sale Price
Product                       Analytics GPS Positioning Prediction  Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner  3325000.0             0.0   700000.0  350000.0
                Emma Gordian  5775000.0        350000.0        0.0  490000.0
Edward Thorp    Elon Tusk     3675000.0             0.0   700000.0       0.0
                Larry Pager   2275000.0             0.0   700000.0  350000.0
                Will Grates   2450000.0             0.0        0.0  350000.0

In [16]:
# Play around whith what are columns and rows
pd.pivot_table(df,index=['Account Manager','Contact','Product'],values=['Sale Price'],aggfunc=[np.sum,np.mean],fill_value=0)

                                                    sum       mean
                                             Sale Price Sale Price
Account Manager Contact      Product
Claude Shannon  Cindy Phoner Analytics          6650000  3325000.0
                             Prediction          700000   700000.0
                             Tracking            350000   350000.0
                Emma Gordian Analytics         11550000  5775000.0
                             GPS Positioning     350000   350000.0
                             Tracking            490000   490000.0
Edward Thorp    Elon Tusk    Analytics          7350000  3675000.0
                             Prediction          700000   700000.0
                Larry Pager  Analytics          4550000  2275000.0
                             Prediction          700000   700000.0
                             Tracking            350000   350000.0
                Will Grates  Analytics          2450000  2450000.0
                             Tracking            350000   350000.0

In [17]:
#Use margins to sumarize
pd.pivot_table(df,index=['Account Manager','Contact','Product'],values=['Sale Price'],aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

                                                    sum          mean
                                             Sale Price    Sale Price
Account Manager Contact      Product
Claude Shannon  Cindy Phoner Analytics          6650000  3.325000e+06
                             Prediction          700000  7.000000e+05
                             Tracking            350000  3.500000e+05
                Emma Gordian Analytics         11550000  5.775000e+06
                             GPS Positioning     350000  3.500000e+05
                             Tracking            490000  4.900000e+05
Edward Thorp    Elon Tusk    Analytics          7350000  3.675000e+06
                             Prediction          700000  7.000000e+05
                Larry Pager  Analytics          4550000  2.275000e+06
                             Prediction          700000  7.000000e+05
                             Tracking            350000  3.500000e+05
                Will Grates  Analytics          2450000  2.450000e+06
                             Tracking            350000  3.500000e+05
All                                            36540000  2.149412e+06