# Useful Methods to apply in a single column

In [1]:
import pandas as pd
import numpy as np

# apply()

In [2]:
df = pd.read_csv('../jupyter_notebooks/03-Pandas/tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [3]:
#last 4 digits of the credit card
#    to get the last 4 characters of a string: 
'this is a text string'[-4:]

'ring'

In [6]:
#     to change 'CC number' into string
str(df['CC Number'])

'0      3560325168603410\n1      4478071379779230\n2      6011812112971322\n3      4676137647685994\n4      4832732618637221\n             ...       \n239    5296068606052842\n240    3506806155565404\n241    6011891618747196\n242       4375220550950\n243    3511451626698139\nName: CC Number, Length: 244, dtype: int64'

In [7]:
# not quite, so build a custom function; then apply() it to the column
def last_four(num):
    return str(num)[-4:]

In [8]:
last_four(1234567890)

'7890'

In [9]:
#   do the magic
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: str

In [10]:
# save it as a column
df['last_four'] = df['CC Number'].apply(last_four)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221

In [11]:
# qualify the restaurant as "$", "$$", "$$$"
def yelp(price):
    if price < 10:
        return "$"
    elif price < 20:
        return "$$"
    else:
        return "$$$"

In [12]:
yelp(5)

'$'

In [13]:
yelp(15)

'$$'

In [14]:
yelp(25)

'$$$'

In [15]:
df['yelp'] = df['total_bill'].apply(yelp)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,$$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,$$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2842,$$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,5404,$$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,7196,$$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,0950,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8139,$$

In [ ]:
# try operating more than one column. Create the 'tip%' column.

In [18]:
def tip_percentage(total, tip):
    return round(tip/total*100,2)

In [19]:
tip_percentage(16.99, 1.01)

5.94

In [20]:
df['tip%'] = (df['total_bill'],df['tip']).apply(tip_percentage)

AttributeError: 'tuple' object has no attribute 'apply'

In [ ]:
# so, we'll need a little bit more help. See Multiple columns notebook.